dist: bionic
addons:
 apt:
  packages: [doxygen, graphviz]
language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip3 install --upgrade pip
  - pip3 install setuptools
  - pip3 install Sphinx
  - pip3 install platformio
  - platformio update

script:
  - make -C test
  - make -C docs html linkcheck
  - git diff --exit-code

notifications:
  email:
    recipients:
      - secure: "jM21ulWU/+fLWX34yZecZnxCT8KJJTtlxmfuFze/dbfbnWagHNlV8ejNw+LhyaVgyOf5eJPgDL8QROZL8OJNOO8MpSw+x6s9t67ouMtH/47MvxNfBWozH/M2RC9F8Iu2fjV1mn8pfBUr0AYUmtBUVGVBmHCGo/2DyzcyeUDaEInapBNXO36HZdzE4lky7brZbX+ANrasK3XIRIcZ/1v6NYGTILu8UAGkJ2DAWgP9KID0YSJyYkP6S+SMXUA1Zq5qK2npFbHYMPWOwcCu0G8tiMzyr4B/93jXl32oqBjYJMB4p+fduKq85TRONZSH2VdxxrsTlcxuSaF3Q27ysshUuMmZF+X64Pd1cL/xCCbdHx8fm9uwGlLSg9LfRFWoSD7hrnxpIscOBWrBIWLY5UcseKLBut1ZUv6SMdVAHzsPyrz14gHcVK+veE4K7HhLWVZqVTUdIHoJvFEqL2b+tJE4F8KbS/K/hngbVNJylFHbl46RPmSLkaIdwoSpsGxTHWI/ImxCy5Hr+FLnRmzVj9WZmEbdU+N5OT1yNoRnaYgP8uTIEuJtlZoJqyOULPWFH45uWyTz5QWhHEzFHg9Zi+hxjizF3EQlQzkMPIbiPEvRbuoXvyOpGlfmxACZ8vAvnZJpiqOAoS1NFkMthXWU6eY2XmSQA3ZxG/wkNc1w5Jr6CAs="
